.create-env-file: &create-env-file
  - echo BASE_URL=$BASE_URL >> .env

.get_report-file: &get_report-file
  artifacts:
    when: always
    paths:
      - playwright-report/
      - test-results/
      - ./playwright-report/results.xml
    reports:
      junit: ./playwright-report/results.xml
    expire_in: 1 day

stages:
  - test

tests:
  stage: test
  image: mcr.microsoft.com/playwright:v1.32.0-focal
  before_script:
    - *create-env-file
  script:
    - npm ci
    - npx playwright test --workers 1 --trace on
  when: manual
  <<: *get_report-file